### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabF-Team1#10]
EDIT: Please don't create and use branches. I don't want to merge your work for you. There is no need to create a branch. A branch is for a separate feature. Just work on master, and when you are ready to push git will tell you if there are any conflicts. If there are merge them locally and then push again. Thank you.

**Comment by jillHuang7** [comment]
May I do the part B? If yes, I will try to finish it by tomorrow.

**Comment by ggorlen** [comment]
Hi all.

**Comment by ggorlen** [comment]
Whoops.  Didn't mean to close.  I'm not on an IDE and forgot to remove the entryList ArrayList.  Glad someone has Eclipse.  Let's ask Masters if it's OK to do this iterator approach.  Seems too easy.  Thanks!

**Comment by karlnicholas** [comment]
As an aside, the **assert** only works if you enable it, which is generally only done for debugging. I don't know if you meant to have the assert actually check or if you're putting debug statements in. See SO post below.

http://stackoverflow.com/questions/7865241/assertion-not-working

**Comment by ggorlen** [comment]
I did use -ea when running the tests.  I prefer assertions to conditionals in private helper methods for a variety of reasons you probably already know about.  If you want to revert to conditionals, no problem here, just a style decision--you're a dev so I definitely trust your opinion :)
G

**Comment by ggorlen** [comment]
Re: iterators--I asked on the forum and we can probably move on to testing or part B without waiting for an answer if folks are ready to go.

**Comment by ggorlen** [comment]
Last remark/note to self: we have some space/tab indentation issues to fix before turning in.  We can wait until everything's done before consolidating this.  Another thing is style on ifs, whether to use brackets or not, spaces, etc.  I do prefer brackets for ifs unless the conditional fits on one line, but I'm flexible overall.  Just wondering if we should allow each method its own style as written or consolidate everything into a single style.

**Comment by karlnicholas** [comment]
Assets are fine me, I just wasn't sure of your level of experience with them. Styles are definitely better consistent, you can't overuse brackets as far as I'm concerned -- I've just been lazy on these group projects. You should add a generic to the iterator and you also won't need the cast for the data. All this comes from an IDE, definitely a must use at some point.

**Comment by ggorlen** [comment]
I'm familiar with Eclipse but never use it for assignments, I write/compile fastest in NP++ and powershell and find that the lack of suggestions keeps me from relying on them, but Eclipse is definitely great.  As mentioned, I'm not too worried about style, so whatever works for you, although we're just lucky in that regard in terms of instructor--some are extremely fickle about style, as you know, so I've become accustomed this semester to being fairly precise in my other classes.  Generic iterator is a great idea, will add that now.

**Comment by ggorlen** [comment]
Another style consideration: whether to javadoc comment the private helper methods or not.  I'd assume not, but again, totally flexible!  I think either way, if someone were to generate javadocs for the class, the private methods will be unlisted.
G

**Comment by karlnicholas** [comment]
Interviewee 1: I use notepad and shell to write code that I hope will someday use artificial intelligence and massive amounts of data to connect a cities infrastructure to self-driving cars so I can go to the launch pad and watch rocket scientists send a mission to Mars. I haven't worked on that stuff because I'm too busy looking up specifics in the man pages.

Interviewee 2; I experimented with machine intelligence code for a simulated Mars lander which I wrote in Eclipse.  I can did that because Eclipse looks things up in the man pages for me and helps me automatically bring in big data and machine learning libraries that others have written in Eclipse.

You figure it out.

In regards to commenting private classes -- just comment everything the same way and be done with it. It's good habit and, yes, the private methods aren't included in the Javadoc but **Eclipse** (there's that word again) knows to add them to its context sensitive helper routines.

**Comment by ggorlen** [comment]
Point well taken re: Eclipse, it's definitely an essential skill for the workplace and super powerful, but I'd tell the employer that if it's a small one-package script without a JAR with dependency export at the end, I enjoy the speed and simplicity of NP++ or vim for personal projects to keep my syntax/library/method memory fresh.  Not to mention NP is a few steps closer to whiteboarding, so it's good to be able to work without autocompile and syntax highlighting as well as with.

Sure, I'll revert to javadoc style for the private comments.  I plan to look at Part B today if you're game!
Greg

**Comment by ggorlen** [comment]
Using an iterator for iterative traversals is permitted, per the instructor, so I think we're pretty much done writing this class if I'm not mistaken.

Cheers,
G

**Comment by karlnicholas** [comment]
Yes, looks like. I updated the Javadoc for compilation issues, but seems to pass all tests and looks good.
