### ISSUE TITLE
assignment submission

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabF-Team1#13]
please review zip file in release and if ok then I will upload it (unless you want to)

**Comment by ggorlen** [comment]
Can't find any problems!  Great working with you.  Don't care who uploads it.  Here's my notes on lambdas from CS211s class yesterday if you're curious.  I figured this assignment was a nice excuse to try it out, and although I never think to do any functional programming in Java, it's actually not too bad: https://github.com/ggorlen/ccsf/blob/master/cs211s/week15_classnotest.txt

**Comment by karlnicholas** [comment]
CS111C-META-FALL-2016 ->Assignment ->Lab F: Trees and Big Data
________________________________________
You have submitted an assignment submission for 'Lab F: Trees and Big Data'.
You can see the status of your assignment submission.

**Comment by karlnicholas** [comment]
Group: Karl Nicholas and Greg Gorlen
great job! excellent use of functional interfaces! great explanations in Part B- nice extra work to delve into the explanations behind it!
-3 in the getAll methods, you should use the sorted nature of the tree to reduce the vertices that need to be searched- once you reach a certain place in the inordrder traversal using the iterator, you can stop- because you know there won't be any more possible values after that point
-6 similar in the get all less than methods- for example, if a current value is greater than or equal to the target, you don't need to continue processing the right tree
+20 extra credit

**Comment by ggorlen** [comment]
Ah, yeah, I thought about as much.  That would probably have improved our speed a lot.  Good to know and thanks for taking the time to update the code!
Greg
