### ISSUE TITLE
1. Write an iterative addEntryHelperIterative method. (20 points)

### ISSUE THREAD

**Issue by karlnicholas** [CS111C-META-FALL-2016/LabF-Team1#3]
* In the BinarySearchTreeWithDups class, we override the add method to call a new private addEntryHelper method. 
  * You will write this helper method. 
  * The helper method allows duplicate entries to be added, using the algorithm described above.
  * Important: This method must be written iteratively (not recursively) in order for Part B to run.
  * I recommend reviewing the addEntry method in BinarySearchTree class and then thinking about how to modify it.

**Comment by karlnicholas** [comment]
fails on dups.

**Comment by ggorlen** [comment]
Hi all--I can't figure out what about the addEntryHelper fails on dupes.  Looks like it works fine to me based on the instructor's test code.  Apologies if I'm missing something obvious!

**Comment by karlnicholas** [comment]
Hi,

It should allow the same letter .. “A” and “A”. Right now I think that only one “A” gets added. I’ll look again in a second .. have to pull it up.

**Comment by karlnicholas** [comment]
Yea, looks like it’s adding dups ok. I’ll have to look closer to see what the problem I was having was. Thanks for checking.

**Comment by karlnicholas** [comment]
I sorted out what I was doing wrong and fixed up the code a bit.
